language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g bower
deploy:
  - provider: releases
    api_key:
      secure: clTbZ/sxBGGhmAkg0+wFuBez0Y4LpGZhg6+6IH816oq7bAVGG1vX4vfgruzCCHcwy1Q1Ypu9AoZR2hvNro8soQvqs2v8ZuHB5ePEeDLzcfgYdYF6I7sSQdHTBoEFc7jdbMsSx2UkdZkJLmMpWlIe/J6sgCPsZhUQ3t+8fD/2hCHquUmrC7RA+tT1FrPQNXnyRDlWYbcfV9x5p7Nv//a785AMGjmkS1J/R7SmUp6GUtQkkOQ+6CZrnhto5uVnFldDzMMMW1c9CNFGuql9J2qpKMd+dAwJrw8Ds6iqz9PjpAClzAFZLSBTPXPt6DgqtwtyerP6F28tXJdvmr/wbFhK31ovc3qz8VJ4coALZP5z1cnKSdrQIx1IAqtREfAnbgK4G0ak9uiQCdCcwjPuUqhDNYhSasAo042Kkv9vrWDg2lC9w66ZR1Xjyr95zDeG7ZVgOt/I5zOOGC25OskJ+OVBOyKpyqjTFtVBlgHHCz0RXjDq9VVvMg7TXafs0XBqVGl0L1HdcfDCIeylaa2oDnU1q5dCeQxfxebXiK374mqiyXYLtFbdDgmDzt4kB2rYKSOsHJfjO5UFBZCa80oZTNqt/TVTiQByLUx46BW1vUjc85UYEup8kuq18rgnqOzkQ0Q2FQGdZ+KphQr4tbq/Ap+nIJF1Yh19jgPqC3IYXoyRrEw=
    file:
      - "dist/string-format.js"
      - "dist/string-format.min.js"
    on:
      tags: true
      repo: cruikshj/string-format
  - provider: npm
    email: cruikshj@live.com
    api_key:
      secure: "IbnU//6k9y663Jr+8hP9suiDfxSmyzELxrvv72JpnAk/ot5kLotRVrP72/2c/1K7huWt2VU5A5hJ8GHU7BMD1cei7ryIMf3XBMhWlnNzYlf+BLRk/Lr7rkHvi7kaLKz3HTDb9Qkh1fnWg24Dr+c9dbIm010bkl/ovgIbaHF7DhrBA7/tKGDcCvKAxWGujvjMi6XvctPYDZrEhI8/rmlAPfPboTLAn/6rqhi3N5ZO7H18jaiQRtx+zmZEkqAKYgSnEC1b6fDViKRN/hv4OD4os/si8hx3i/tcCUqALWJKf4qqESdkCIB3iGhcPsMl1dp+0/xpQ4RwzIP8OhfuCtNGvWTfV8coOrEbNVm1VcYNNfksdLlrJPI+KiKVafB2pTrkIn8N0PtQbKMDLWalQjMUF+cbR53K1hEAoTvJp43cQL2Wv+HXUuDcenrj6jQAsqWiMAK6flsbuZ+PjgSeXPYtSEPbqI8o1ivfRpGSIzysKx9fxL5p+TWYVCl/G9r29aZeWChXLovQ3mTujvvHY5zSKoXX7YvomC2EZMhlzwKksMh+Mi+JX9uaiqrxal7Fi5ou5GUw8tB7KGYFMy+mcP3bm+CrOHp4Sx8vHesvM3FxPkNj3ipJTHIhbyeKtDrNoKjsDzoMLKlfJmDgnRwWb+TsyF+0d9oVkcFNhfy4WKEFmaE="
    on:
      tags: true
      repo: cruikshj/string-format
