language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g bower
deploy:
  - provider: releases
    api_key:
      secure: clTbZ/sxBGGhmAkg0+wFuBez0Y4LpGZhg6+6IH816oq7bAVGG1vX4vfgruzCCHcwy1Q1Ypu9AoZR2hvNro8soQvqs2v8ZuHB5ePEeDLzcfgYdYF6I7sSQdHTBoEFc7jdbMsSx2UkdZkJLmMpWlIe/J6sgCPsZhUQ3t+8fD/2hCHquUmrC7RA+tT1FrPQNXnyRDlWYbcfV9x5p7Nv//a785AMGjmkS1J/R7SmUp6GUtQkkOQ+6CZrnhto5uVnFldDzMMMW1c9CNFGuql9J2qpKMd+dAwJrw8Ds6iqz9PjpAClzAFZLSBTPXPt6DgqtwtyerP6F28tXJdvmr/wbFhK31ovc3qz8VJ4coALZP5z1cnKSdrQIx1IAqtREfAnbgK4G0ak9uiQCdCcwjPuUqhDNYhSasAo042Kkv9vrWDg2lC9w66ZR1Xjyr95zDeG7ZVgOt/I5zOOGC25OskJ+OVBOyKpyqjTFtVBlgHHCz0RXjDq9VVvMg7TXafs0XBqVGl0L1HdcfDCIeylaa2oDnU1q5dCeQxfxebXiK374mqiyXYLtFbdDgmDzt4kB2rYKSOsHJfjO5UFBZCa80oZTNqt/TVTiQByLUx46BW1vUjc85UYEup8kuq18rgnqOzkQ0Q2FQGdZ+KphQr4tbq/Ap+nIJF1Yh19jgPqC3IYXoyRrEw=
    file:
      - "dist/string-format.js"
      - "dist/string-format.min.js"
    on:
      tags: true
      repo: cruikshj/string-format
  - provider: npm
    email: cruikshj@live.com
    api_key:
      secure: cpGGZabE/irjJgReErNu4S0ZNN9FyRs2MSc4WeF4cfeI6VdenJYuw81S9HCXdeHoQe9JqTAi6+2fmovXerea6PZAq2XGu68utuMPbxGPlXakfdyVsMaVbYlbpx3hir1+mbKNoNQiJgX4T/pdqvU/VZFNtxdthcqY6gnRy2uWNXvh3OH0+Koj1ng8JvDABg74xd+Q6vXFAWeatQTf1XgYYeEQ+s+zifMGIFLsfsKqYV8sJFjbD3ASkdbWfyE34zMyh02AMvhldeZXQj3+8m80g0i8qelw+hPtFOFqNVrCfpkeREeEnf/HXe6/BEZaHSwkt9AR2nTFzp4UJqEdPIV8bctyMO8fhcrAV80d/135UTfBjFlRhRZWuRGKJOF7vVN5Ej1I97pJwqRAqzpxIluhlR7YjlYpePpbCC10zcjrUXrxY3ty9kPnJMwSQzQFCaYBH0rb6prNwhHX5gd4icCaAFO62xkpmyES+Ul2VBa7wA5OKRCLA+KyBvGpMRFA1zmwHmJmvgXyiUfQJrgV+0SN0MdwitfAczswEMDRV0+R02ZpTOM96aq3a09JKeUECGRI6OD3YWPKz8gL0rUGQNpF7OOMipBEl2qYpWmu9eqql00iVdV22XxMiJM4gMbYwbj6WA24vZWmVH2xh328/rKN11CrSn5hnGa61mxvU4DnXOc=
    on:
      tags: true
      repo: cruikshj/string-format
